### ISSUE TITLE
Cannot GET /login/facebook/callback.

### ISSUE THREAD

**Issue by eimantas** [IBM-Swift/Kitura-CredentialsFacebook#30]
I have implemented the facebook login as per the README tutorial, however after I get redirected back to my app I get the `Cannot GET /login/facebook/callback.` message. If I attempt to refresh the page, then I get the blank page (so I assume the login was successful).

Any clues as to what might be the problem?

**Comment by svanimpe** [comment]
I had a similar problem when first using Kitura-Credentials. Did you call the `/login/facebook` endpoint directly, instead of using the failure redirect? If so, the credentials middleware may not know where to redirect the user back to.

I think you're supposed to use the middleware as follows:

1. Set `credentials.options["failureRedirect"] = "/login/facebook"`
2. Use `credentials` as a middleware for endpoints you want to use authentication for. In my case, that's everything under `/web/`, so I set `router.all("/web", middleware: [session, credentials])`.

The middleware will then check for authentication and if the user isn't authenticated yet, store the endpoint the user was attempting to access (say `/web/home`) and redirect to `/login/facebook`. When authentication is successful, the callback will then look up the original endpoint the user was trying to access (`/web/home`) and redirect back to there.

This setup works great for me.

**Comment by eimantas** [comment]
@svanimpe thanks for the response!

It was actually the problem on the second item in your list. I didn't add the middleware to all routes. The way I presumed it worked is that if added to all routes, I would have a `userProfile` in request as an optional. It's `nil` if user is anonymous and it has a value if user is authorized. However adding middleware to all routes (I was attempting to add it to `"/"`), I got only blank screens. 

The guys at ibm made a new release (I think it was 1.7.2) that changes the behaviour. Now you can add the middleware to the root path and check for the presence of user profile in `request` parameter and everything renders correctly!
