### ISSUE TITLE
Tiny profile pictures

### ISSUE THREAD

**Issue by svanimpe** [IBM-Swift/Kitura-CredentialsFacebook#31]
When using `options: ["fields": "picture"]`, the profile picture returned is only 50px50px, which is too tiny for most use cases. [Facebook's API](https://developers.facebook.com/docs/graph-api/reference/user/picture/) seems to support larger sizes. Is it possible to fetch a larger image by default?

**Comment by shmuelk** [comment]
Under the covers we are simply invoking the Facebook Graph API against the logged in user (i.e. /me). The fields that are provided to CredentialsFacebook are simply passed to Facebook's API.

Instead of requesting the picture field, why not try picture.type(large)?

Facebook now supports a qualifier of some of the fields.

**Comment by svanimpe** [comment]
Worked perfectly, thanks!
